spring:
  profiles:
    active: prod
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

logging:
  level:
    root: INFO
    com.spkt: INFO
    org.springframework: WARN
    org.hibernate: WARN

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain